spring.application.name: APIGateway-Service

server.port: 8080
jwt:
  secretKey: "ashiour0w1319=45r@(_)O)#(_5jljoijrofjmcjfjejdarir023ofk8"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=2


        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/v1/accounts/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter


        - id: transitions-service
          uri: lb://TRANSITIONS-SERVICE
          predicates:
            - Path=/api/v1/transaction/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter


        - id: notifications-service
          uri: lb://NOTIFICATIONS-SERVICE
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - StripPrefix=2

        - id: loan-service
          uri: lb://LOAN-SERVICE
          predicates:
            - Path=/api/v1/loans/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter


        - id: cards-service
          uri: lb://CARDS-SERVICE
          predicates:
            - Path=/api/v1/cards/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter



        - id: billPay-service
          uri: lb://BILLPAY-SERVICE
          predicates:
            - Path=/api/v1/billPays/**
          filters:
            - StripPrefix=2



        - id: auth-service
          uri: lb:/AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2